
[connections.supabase]
SUPABASE_URL = "https://igfzjpgptsdylmkoutnl.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlnZnpqcGdwdHNkeWxta291dG5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0MDE5OTksImV4cCI6MjA3MTk3Nzk5OX0.p7Ddi_dSYBs0kXyHgyOxfSVkW5fS9EEVCscGoEapjqA"


